% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Jul-2021 22:07:04
%  MATLAB version: 9.10.0.1602886 (R2021a)
% -------------------------------------------------------------------
saveVarsMat = load('mlc_save.mat');

mlc = saveVarsMat.mlc; % <1x1 MLC> unsupported class

clear saveVarsMat;
